apiVersion: v1
kind: LimitRange
metadata:
  name: mem-cpu-limit-range
  namespace: url-shortener
spec: 
  limits:
  - default:
      cpu: 500m
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    max:
      cpu: "1"
      memory: 1Gi
    type: Container